#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 44b0b039-c910-460f-b7d9-4d46a2f57446
# Source File: C:\Users\b_mag\Documents\SAPIEN\Files\exchange Search Form.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.155
     Generated on:       11/27/2018 10:28 AM
     Generated by:       Gary Cook
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-exchange_Search_Form_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formQuestExchangeQueryBu = New-Object 'System.Windows.Forms.Form'
	$buttonCopyToClipboard = New-Object 'System.Windows.Forms.Button'
	$buttonVerifyEmailFormat = New-Object 'System.Windows.Forms.Button'
	$queryresult = New-Object 'System.Windows.Forms.TextBox'
	$labelQuery = New-Object 'System.Windows.Forms.Label'
	$bodyep = New-Object 'System.Windows.Forms.CheckBox'
	$subjectep = New-Object 'System.Windows.Forms.CheckBox'
	$fromuser = New-Object 'System.Windows.Forms.TextBox'
	$labelFromUser = New-Object 'System.Windows.Forms.Label'
	$bodykw = New-Object 'System.Windows.Forms.TextBox'
	$labelBodyKeywords = New-Object 'System.Windows.Forms.Label'
	$subjectkw = New-Object 'System.Windows.Forms.TextBox'
	$labelSubjectKeywords = New-Object 'System.Windows.Forms.Label'
	$enddate = New-Object 'System.Windows.Forms.DateTimePicker'
	$labelEndDate = New-Object 'System.Windows.Forms.Label'
	$labelStartDate = New-Object 'System.Windows.Forms.Label'
	$startdate = New-Object 'System.Windows.Forms.DateTimePicker'
	$labelDateRange = New-Object 'System.Windows.Forms.Label'
	$buttonExit = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$emailvalidated = $false
	$formQuestExchangeQueryBu_Load={
		#TODO: Initialize Form Controls here
		update_query
	}
	
	$startdate_ValueChanged={
		#TODO: Place custom script here
		update_query
	}
	
	$startdate_ControlAdded=[System.Windows.Forms.ControlEventHandler]{
	#Event Argument: $_ = [System.Windows.Forms.ControlEventArgs]
		#TODO: Place custom script here
		update_query
	}
	
	$enddate_ControlAdded=[System.Windows.Forms.ControlEventHandler]{
	#Event Argument: $_ = [System.Windows.Forms.ControlEventArgs]
		#TODO: Place custom script here
		update_query
	}
	
	$enddate_ValueChanged={
		#TODO: Place custom script here
		update_query
	}
	
	$subjectkw_TextChanged={
		#TODO: Place custom script here
		update_query
	}
	
	$subjectep_CheckedChanged={
		#TODO: Place custom script here
		update_query
	}
	
	$bodyep_CheckedChanged={
		#TODO: Place custom script here
		update_query
	}
	
	$bodykw_TextChanged={
		#TODO: Place custom script here
		update_query
	}
	
	$buttonVerifyEmailFormat_Click={
		#TODO: Place custom script here
		$regex = @"
^[a-zA-Z0-9.!£#$%&'^_`{}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$
"@
		if ($fromuser.Text -cmatch $regex)
		{
			$emailvalidated = $true
			update_query
		}
		else
		{
		#Add-Type -AssemblyName "System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
		[void][System.Windows.Forms.MessageBox]::Show('Not a Valid Email Address', 'Email Not Validated') # Casting the method to [void] suppresses the output. 	
		}
		
	
	}
	
	
	function update_query
	{
		[string]$sdate = $startdate.Value.Date.ToShortDateString()
		[string]$edate = $enddate.value.Date.ToShortDateString()
		$datecheck = "Sent:" + $sdate + ".." + $edate 
		if ($subjectkw.text -ne "")
		{
			if ($subjectep.Checked -eq $true)
			{
				$subjectcheck = "Subject:""" + $subjectkw.Text + """"
			}
			else
			{
				$subjectcheck = "Subject:'" + $subjectkw.Text + "'"
			}
			
		}
		else
		{
		$subjectcheck = ""	
		}
		if ($bodykw.text -ne "")
		{
			if ($bodyep.Checked -eq $true)
			{
				$bodycheck = "Body:""" + $bodykw.Text + """"
			}
			else
			{
				$bodycheck = "Body:'" + $bodykw.Text + "'"
			}
			
		}
		else
		{
		$bodycheck = ""	
		}
		if ($emailvalidated -eq $true)
		{
		$emailcheck = "From:" + $fromuser.Text + ""	
		}
		
		if ($datecheck -ne "")
		{
			$queryresult.text = $datecheck 
		}
		if ($subjectcheck -ne "")
		{
			$queryresult.text = $queryresult.text + " AND " + $subjectcheck
		}
		if ($bodycheck -ne "")
		{
			$queryresult.text = $queryresult.text + " AND " + $bodycheck
		}
		if ($emailvalidated -eq $true)
		{
			$queryresult.text = $queryresult.text + " AND " + $emailcheck
		}
	
	}
	$fromuser_TextChanged={
		#TODO: Place custom script here
		$emailvalidated = $false
		update_query
	}
	
	$buttonCopyToClipboard_Click={
		#TODO: Place custom script here
		[System.Windows.Forms.Clipboard]::SetText($queryresult.text)
	}
	
	$buttonExit_Click={
		#TODO: Place custom script here
		$global:query = $queryresult.Text
		$script:rquery = $queryresult.Text
		
	}
	
	$formQuestExchangeQueryBu_FormClosed=[System.Windows.Forms.FormClosedEventHandler]{
	#Event Argument: $_ = [System.Windows.Forms.FormClosedEventArgs]
		#TODO: Place custom script here
		[System.Windows.Forms.Clipboard]::SetText($queryresult.text)
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formQuestExchangeQueryBu.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonCopyToClipboard.remove_Click($buttonCopyToClipboard_Click)
			$buttonVerifyEmailFormat.remove_Click($buttonVerifyEmailFormat_Click)
			$bodyep.remove_CheckedChanged($bodyep_CheckedChanged)
			$subjectep.remove_CheckedChanged($subjectep_CheckedChanged)
			$fromuser.remove_TextChanged($fromuser_TextChanged)
			$bodykw.remove_TextChanged($bodykw_TextChanged)
			$subjectkw.remove_TextChanged($subjectkw_TextChanged)
			$enddate.remove_ValueChanged($enddate_ValueChanged)
			$enddate.remove_ControlAdded($enddate_ControlAdded)
			$startdate.remove_ValueChanged($startdate_ValueChanged)
			$startdate.remove_ControlAdded($startdate_ControlAdded)
			$buttonExit.remove_Click($buttonExit_Click)
			$formQuestExchangeQueryBu.remove_FormClosed($formQuestExchangeQueryBu_FormClosed)
			$formQuestExchangeQueryBu.remove_Load($formQuestExchangeQueryBu_Load)
			$formQuestExchangeQueryBu.remove_Load($Form_StateCorrection_Load)
			$formQuestExchangeQueryBu.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formQuestExchangeQueryBu.SuspendLayout()
	#
	# formQuestExchangeQueryBu
	#
	$formQuestExchangeQueryBu.Controls.Add($buttonCopyToClipboard)
	$formQuestExchangeQueryBu.Controls.Add($buttonVerifyEmailFormat)
	$formQuestExchangeQueryBu.Controls.Add($queryresult)
	$formQuestExchangeQueryBu.Controls.Add($labelQuery)
	$formQuestExchangeQueryBu.Controls.Add($bodyep)
	$formQuestExchangeQueryBu.Controls.Add($subjectep)
	$formQuestExchangeQueryBu.Controls.Add($fromuser)
	$formQuestExchangeQueryBu.Controls.Add($labelFromUser)
	$formQuestExchangeQueryBu.Controls.Add($bodykw)
	$formQuestExchangeQueryBu.Controls.Add($labelBodyKeywords)
	$formQuestExchangeQueryBu.Controls.Add($subjectkw)
	$formQuestExchangeQueryBu.Controls.Add($labelSubjectKeywords)
	$formQuestExchangeQueryBu.Controls.Add($enddate)
	$formQuestExchangeQueryBu.Controls.Add($labelEndDate)
	$formQuestExchangeQueryBu.Controls.Add($labelStartDate)
	$formQuestExchangeQueryBu.Controls.Add($startdate)
	$formQuestExchangeQueryBu.Controls.Add($labelDateRange)
	$formQuestExchangeQueryBu.Controls.Add($buttonExit)
	$formQuestExchangeQueryBu.AcceptButton = $buttonExit
	$formQuestExchangeQueryBu.AutoScaleDimensions = '6, 13'
	$formQuestExchangeQueryBu.AutoScaleMode = 'Font'
	$formQuestExchangeQueryBu.ClientSize = '891, 302'
	$formQuestExchangeQueryBu.FormBorderStyle = 'FixedDialog'
	$formQuestExchangeQueryBu.MaximizeBox = $False
	$formQuestExchangeQueryBu.MinimizeBox = $False
	$formQuestExchangeQueryBu.Name = 'formQuestExchangeQueryBu'
	$formQuestExchangeQueryBu.StartPosition = 'CenterScreen'
	$formQuestExchangeQueryBu.Text = 'Quest Exchange Query Builder'
	$formQuestExchangeQueryBu.add_FormClosed($formQuestExchangeQueryBu_FormClosed)
	$formQuestExchangeQueryBu.add_Load($formQuestExchangeQueryBu_Load)
	#
	# buttonCopyToClipboard
	#
	$buttonCopyToClipboard.Location = '787, 253'
	$buttonCopyToClipboard.Name = 'buttonCopyToClipboard'
	$buttonCopyToClipboard.Size = '92, 39'
	$buttonCopyToClipboard.TabIndex = 17
	$buttonCopyToClipboard.Text = '&Copy to Clipboard'
	$buttonCopyToClipboard.UseCompatibleTextRendering = $True
	$buttonCopyToClipboard.UseVisualStyleBackColor = $True
	$buttonCopyToClipboard.add_Click($buttonCopyToClipboard_Click)
	#
	# buttonVerifyEmailFormat
	#
	$buttonVerifyEmailFormat.Location = '352, 226'
	$buttonVerifyEmailFormat.Name = 'buttonVerifyEmailFormat'
	$buttonVerifyEmailFormat.Size = '138, 23'
	$buttonVerifyEmailFormat.TabIndex = 16
	$buttonVerifyEmailFormat.Text = 'Verify Email Format'
	$buttonVerifyEmailFormat.UseCompatibleTextRendering = $True
	$buttonVerifyEmailFormat.UseVisualStyleBackColor = $True
	$buttonVerifyEmailFormat.add_Click($buttonVerifyEmailFormat_Click)
	#
	# queryresult
	#
	$queryresult.Location = '121, 269'
	$queryresult.Name = 'queryresult'
	$queryresult.ReadOnly = $True
	$queryresult.Size = '659, 20'
	$queryresult.TabIndex = 15
	#
	# labelQuery
	#
	$labelQuery.Location = '13, 267'
	$labelQuery.Name = 'labelQuery'
	$labelQuery.Size = '100, 23'
	$labelQuery.TabIndex = 14
	$labelQuery.Text = 'Query'
	$labelQuery.TextAlign = 'MiddleLeft'
	$labelQuery.UseCompatibleTextRendering = $True
	#
	# bodyep
	#
	$bodyep.Location = '616, 178'
	$bodyep.Name = 'bodyep'
	$bodyep.Size = '104, 24'
	$bodyep.TabIndex = 13
	$bodyep.Text = 'Exact Phrase'
	$bodyep.UseCompatibleTextRendering = $True
	$bodyep.UseVisualStyleBackColor = $True
	$bodyep.add_CheckedChanged($bodyep_CheckedChanged)
	#
	# subjectep
	#
	$subjectep.Location = '616, 131'
	$subjectep.Name = 'subjectep'
	$subjectep.Size = '104, 24'
	$subjectep.TabIndex = 12
	$subjectep.Text = 'Exact Phrase'
	$subjectep.UseCompatibleTextRendering = $True
	$subjectep.UseVisualStyleBackColor = $True
	$subjectep.add_CheckedChanged($subjectep_CheckedChanged)
	#
	# fromuser
	#
	$fromuser.Location = '121, 226'
	$fromuser.Name = 'fromuser'
	$fromuser.Size = '224, 20'
	$fromuser.TabIndex = 11
	$fromuser.add_TextChanged($fromuser_TextChanged)
	#
	# labelFromUser
	#
	$labelFromUser.Location = '13, 226'
	$labelFromUser.Name = 'labelFromUser'
	$labelFromUser.Size = '100, 23'
	$labelFromUser.TabIndex = 10
	$labelFromUser.Text = 'From User'
	$labelFromUser.UseCompatibleTextRendering = $True
	#
	# bodykw
	#
	$bodykw.Location = '121, 178'
	$bodykw.Name = 'bodykw'
	$bodykw.Size = '488, 20'
	$bodykw.TabIndex = 9
	$bodykw.add_TextChanged($bodykw_TextChanged)
	#
	# labelBodyKeywords
	#
	$labelBodyKeywords.Location = '13, 178'
	$labelBodyKeywords.Name = 'labelBodyKeywords'
	$labelBodyKeywords.Size = '100, 23'
	$labelBodyKeywords.TabIndex = 8
	$labelBodyKeywords.Text = 'Body Keywords'
	$labelBodyKeywords.UseCompatibleTextRendering = $True
	#
	# subjectkw
	#
	$subjectkw.Location = '121, 131'
	$subjectkw.Name = 'subjectkw'
	$subjectkw.Size = '488, 20'
	$subjectkw.TabIndex = 7
	$subjectkw.add_TextChanged($subjectkw_TextChanged)
	#
	# labelSubjectKeywords
	#
	$labelSubjectKeywords.Location = '13, 131'
	$labelSubjectKeywords.Name = 'labelSubjectKeywords'
	$labelSubjectKeywords.Size = '100, 17'
	$labelSubjectKeywords.TabIndex = 6
	$labelSubjectKeywords.Text = 'Subject Keywords'
	$labelSubjectKeywords.UseCompatibleTextRendering = $True
	#
	# enddate
	#
	$enddate.Location = '121, 77'
	$enddate.Name = 'enddate'
	$enddate.Size = '200, 20'
	$enddate.TabIndex = 5
	$enddate.add_ValueChanged($enddate_ValueChanged)
	$enddate.add_ControlAdded($enddate_ControlAdded)
	#
	# labelEndDate
	#
	$labelEndDate.Location = '37, 77'
	$labelEndDate.Name = 'labelEndDate'
	$labelEndDate.Size = '56, 16'
	$labelEndDate.TabIndex = 4
	$labelEndDate.Text = 'End Date'
	$labelEndDate.UseCompatibleTextRendering = $True
	#
	# labelStartDate
	#
	$labelStartDate.Location = '37, 42'
	$labelStartDate.Name = 'labelStartDate'
	$labelStartDate.Size = '63, 16'
	$labelStartDate.TabIndex = 3
	$labelStartDate.Text = 'Start Date'
	$labelStartDate.UseCompatibleTextRendering = $True
	#
	# startdate
	#
	$startdate.Location = '121, 42'
	$startdate.Name = 'startdate'
	$startdate.Size = '200, 20'
	$startdate.TabIndex = 2
	$startdate.add_ValueChanged($startdate_ValueChanged)
	$startdate.add_ControlAdded($startdate_ControlAdded)
	#
	# labelDateRange
	#
	$labelDateRange.Location = '13, 13'
	$labelDateRange.Name = 'labelDateRange'
	$labelDateRange.Size = '67, 18'
	$labelDateRange.TabIndex = 1
	$labelDateRange.Text = 'Date Range'
	$labelDateRange.UseCompatibleTextRendering = $True
	#
	# buttonExit
	#
	$buttonExit.Anchor = 'Bottom, Right'
	$buttonExit.DialogResult = 'OK'
	$buttonExit.Location = '804, 12'
	$buttonExit.Name = 'buttonExit'
	$buttonExit.Size = '75, 23'
	$buttonExit.TabIndex = 0
	$buttonExit.Text = 'E&xit'
	$buttonExit.UseCompatibleTextRendering = $True
	$buttonExit.UseVisualStyleBackColor = $True
	$buttonExit.add_Click($buttonExit_Click)
	$formQuestExchangeQueryBu.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formQuestExchangeQueryBu.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formQuestExchangeQueryBu.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formQuestExchangeQueryBu.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formQuestExchangeQueryBu.ShowDialog()

} #End Function

#Call the form
Show-exchange_Search_Form_psf | Out-Null
